name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Deploy to Render
        env:
          DEPLOY_URL: ${{ secrets.RENDER_HOOK_URL }}
        run: |
          curl -X POST "$DEPLOY_URL"

        #  Comment to test workflow